### ISSUE TITLE
documentation drive: Quick ideas re: README

### ISSUE THREAD

**Issue by PragmaticCypher** [ssbc/ssb-minimal-pub-server#1]
Hey,

As a non-user of the project, I'm checking over the README of the project.  A couple of ideas which may help clarify this project for newbies:

 - Does the project supply command line tools like the ssb-server?  or is it just an NPM module?
 - Maybe link to projects which use it?

**Comment by arj03** [comment]
Hi

Thanks for the feedback.

I added a line, is that better? :)

I should try and make a PR for https://github.com/ahdinosaur/ssb-pub to use this. Havn't gotten around to doing that yet.

**Comment by PragmaticCypher** [comment]
I think so :)

Maybe this will make things clearer as well?  I may have gotten the install instructions wrong

https://john.server.ky/src/fork/ssb-minimal-pub-server/commit/?h=update-readme&id=0f5bb24f4844f104b92d561726d3eaf6b75fedaf

**Comment by arj03** [comment]
Thanks, added 🤗
